name: Input and Output
# qual evento ira dar o trigger na pipeline
on:
  # push:
  #   branches: ["main"]
  workflow_dispatch:
    inputs:
      version:
        type: string
        default: "dev"
        required: true
        description: "Release Version"
      do_deploy:
        type: boolean
        required: true
        description: "Make a deploy"
      enviroment:
        type: choice
        required: true
        description: "Choose the env"
        options:
          - dev
          - homol
          - prod
# env:
#   ENV_WORKFLOW: "ENV WORKFLOW"
jobs:
  input-output-job:
    name: "Input and Output job"
    # onde sera executado a ação
    runs-on: ubuntu-latest
    steps:
      - name: "Print all inputs"
        run: |
          echo "Printing all inputs"
          echo "${{ toJSON(inputs) }}"

    #   - name: Instrala o ffmpeg
    #     run: |
    #       sudo apt update --yes
    #       sudo apt install ffmpeg --yes
    #   - name: "Verifica se existe o ffmpeg"
    #     run: |
    #       ffmpeg --help
    #       echo $ENV_WORKFLOW
    #   - name: Contexto github
    #     env:
    #       GITHUB_CONTEXT: ${{ toJson(github) }}
    #     run: echo "$GITHUB_CONTEXT"
    #   - name: Contexto env
    #     env:
    #       ENV_CONTEXT: ${{ toJson(env) }}
    #     run: echo "$ENV_CONTEXT"
    #   - name: Contexto job
    #     env:
    #       JOB_CONTEXT: ${{ toJson(job) }}
    #     run: echo "$JOB_CONTEXT"
    #   - name: Contexto steps
    #     env:
    #       STEPS_CONTEXT: ${{ toJson(steps) }}
    #     run: echo "$STEPS_CONTEXT"
    #   - name: Contexto runner
    #     env:
    #       RUNNER_CONTEXT: ${{ toJson(runner) }}
    #     run: echo "$RUNNER_CONTEXT"
      # - name: "Segunda ação"
      #   run: echo "Voce criou o seu primeiro workflow"
  # segundo-job:
  #   needs: primeiro-job
  #   name: "Instalação do ambiente NodeJS"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Verificação da versão do Node"
  #       run: node --version
  #     - name: "Definição da versão mais recente do Node"
  #       uses: actions/setup-node@v4
  #       with: 
  #         node-version: "24"
  #     - name: "Verificação da versão do Node depois de atualizar a versao"
  #       run: node --version
